"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Safebox.py']
DATA_FILES = [('assets')]
OPTIONS = {'argv_emulation': False,
 'plist': 'Info.plist',
 'includes': 'PySide.QtCore, PySide.QtGui, Crypto.Cipher',
 'semi_standalone':'False',
 'packages': ('PySide', 'Crypto'),
 'site_packages': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
